### ISSUE TITLE
Question: Does the SecurityVPC.yaml works with specifying any s3 ?

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#15]
Hi,

I used https://github.com/PaloAltoNetworks/AWS-GWLB-VMSeries/blob/main/CFT_2_Firewalls/SecurityVPC.yaml

and executed ,everything gets created without any error. But when I try to ssh to public IP of VM-Series Management not reachable.

Note: I have left blank "AWS S3 Bucket Name containing the VM-Series Bootstrap Information:"

I even added udp to check if i get ping request, but nothing...

niteen-test01-VMSeries-Management

Type | Protocol | Port range | Source | Description - optional
-- | -- | -- | -- | --
SSH | TCP | 22 | 0.0.0.0/0 | –
All UDP | UDP | 0 - 65535 | 0.0.0.0/0 | –
HTTPS | TCP | 443 | 0.0.0.0/0 | –

**Comment by salsop** [comment]
I've just created this only specifying the AMI and EC2 Key Pair, and the VM-Series came online and I could SSH to them. I assume you're using an SSH command like: `ssh admin@1.2.3.4 -i ~/ec2-key-pair.pem`?

Can you let me know what region and what AMI you're using and I can test matching your specific deployment? 

Creating the VMSeries without any S3 Bootstrap will be fine.

**Comment by niteenkole** [comment]
yes using 
ssh admin@1.2.3.4 -i ~/ec2-key-pair.pem

region
ca-central-1

EC2 Instance Type for VM-Series
m5.large

AMI
aws ec2 describe-images --filters "Name=product-code,Values=e9yfvyj3uag5uo5j2hjikv74n" Name=name,Values=PA-VM-AWS*10.0*  --region ca-central-1 --output table --query "Images[*].{Name:Name,AMI:ImageId,State:State}"

using
ami-030be1da75220d4b1

**Comment by niteenkole** [comment]
Hi,

I tired to recreate, now it says.

The system is in maintenance mode. Connect via serial console or with user 'maint' through ssh to access the recovery tool.

**Comment by niteenkole** [comment]
I am good now.Looks like m5.large not supported.Changed it to m5.xlarge and looks good.

**Comment by niteenkole** [comment]
@salsop  thanks for your help.

During testing to reduce cost I was trying to use m5.large looks like that is not supported.

**Comment by salsop** [comment]
That's great, I'm glad you got it sorted, the m5.xlarge is supported with a VM-100 (2x vCPU) BYOL license, but great you got it all working.
