### ISSUE TITLE
Question on using transit GW in account1using RAM to share with say test account2

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#16]
trying to use your below template as it is to test.

https://github.com/PaloAltoNetworks/AWS-GWLB-VMSeries/tree/main/cft%20with%20autoscale/app_stack

Only thing is I want to test setting up app stack in separate account  and use transit GW setup in our security account.TGW is shared from security account using RAM and is visible inside my test account.

Deployment fails saying.
Transit Gateway tgw-0609xxx7 was deleted or does not exist. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidTransitGatewayID.NotFound; Request ID: 80918cdd-5f72-48eb-9200-335a73e6730d; Proxy: null)

shared TGW is visible in this account.

**Comment by niteenkole** [comment]
closing ....

**Comment by lachlanjholmes** [comment]
@niteenkole  what was your fix for this?

**Comment by niteenkole** [comment]
@lachlanjholmes trying to recollect it was almost year back.

**Comment by lachlanjholmes** [comment]
@niteenkole was it the App VPC template uses _AWS::EC2::TransitGatewayAttachment_ resource and not  _AWS::EC2::TransitGatewayVpcAttachment_?

**Comment by lachlanjholmes** [comment]
Hey @niteenkole did you get errors in your cloudwatch logs saying that the lambda from the return route in the Security VPC couldn't create because it couldn't _describeVPCs_ CIDR from the TGW attachment?
