### ISSUE TITLE
Question of panaroma 10.0.2 + on AWS

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#17]
I am trying to get panorama 10.0.2 or like that in AWS 

AWS market place max supported is 9.1.9 .Checking if I am doing something wrong.

if I try community AMI say 
Panorama-AWS-10.0.2-f264c750-1102-41c9-a14d-b54ea51780e4-ami-043b1436d961638fa.4 - ami-01f439875be1959cc
Panorama-AWS-10.0.2

fails saying not supported.

**Comment by salsop** [comment]
Depending on if you're using BYOL, Bundle1 or Bundle2 these commands will list you the relevant AMIs:

For BYOL:
```bash
aws ec2 describe-images --filters "Name=name,Values=PA-VM-AWS-10.0*" "Name=product-code,Values=6njl1pau431dv1qxipg63mvah" --region eu-west-1 --query "Images[*].{Name:Name,AMI:ImageId,State:State}" --output table
```

For BUNDLE1:
```bash
ws ec2 describe-images --filters "Name=name,Values=PA-VM-AWS-10.0*" "Name=product-code,Values=hd44w1chf26uv4p52cdynb2o" --region eu-west-2 --query "Images[*].{Name:Name,AMI:ImageId,State:State}" --output table
```

For BUNDLE2:
```bash
aws ec2 describe-images --filters "Name=name,Values=PA-VM-AWS-10.0*" "Name=product-code,Values=hd44w1chf26uv4p52cdynb2o" --region eu-west-1 --query "Images[*].{Name:Name,AMI:ImageId,State:State}" --output table
```

**Comment by salsop** [comment]
I've just deployed the `ami-01f439875be1959cc` using `m5.4xlarge` to `ca-central-1` OK.

Can you confirm what instance type you're using?

You should have these AMIs available in `ca-central-1`:
![image](https://user-images.githubusercontent.com/29990503/115926671-24302600-a47b-11eb-897b-32e8cfc50df3.png)

**Comment by niteenkole** [comment]
yes i am using ca-central-1
![panorama](https://user-images.githubusercontent.com/44979343/115928242-cb00cc00-a453-11eb-8b8f-4cfb5b93d1ab.png)

**Comment by salsop** [comment]
I think this is because of the instance size you have selected. The `m5.large` isn't a supported instances size, if you chose either `m5.2xlarge` or `m5.4xlarge` this should work

![image](https://user-images.githubusercontent.com/29990503/115928582-45464600-a47e-11eb-81c4-a432ca50dbad.png)

**Comment by niteenkole** [comment]
You correct. Looks good now.

Is there as link  where we can see for each region what is supported, will be helpful for everyone.

Again thank you.

**Comment by niteenkole** [comment]
All good.
