### ISSUE TITLE
Question on cft with autoscale for auth code

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#18]
As per document "before launching the templates"

obtain the auth code for a bundle that supports the number of firewalls that might be required for your deployment.

Does this means this works only for BYOL or am I misunderstanding, want to test for usage based.

**Comment by salsop** [comment]
@niteenkole this should work fine with PAYG the PAYG licensing or BYOL AMIs.

**Comment by niteenkole** [comment]
In Aws I am not able to fire panorama 10+ with EULA it’s just gives me option of BYOL

Any help much appreciated

**Comment by salsop** [comment]
Ah, sorry. I thought you meant the VM-Series. Yes, Panorama is only BYOL license. If you need Evaluation licenses for your testing you can get these from a Palo Alto Networks Partner, or your Palo Alto Networks Account team. 

If you want to email me (salsop@paloaltonetworks.com) your Name, Contact Details, and Organizations Name I can make contact with your account team for them to contact you.

**Comment by niteenkole** [comment]
Ok thanks.

No where it’s documented in aws or even at PA that it’s BYOL.

**Comment by salsop** [comment]
I'll speak to the team and see if we can get this mentioned in the text description too. It is flagged on the AWS Marketplace, but I'll see if we can get this improved in the supporting documentation too.

![image](https://user-images.githubusercontent.com/29990503/116063818-4e513600-a67d-11eb-85ab-2fbcdb45343a.png)

**Comment by niteenkole** [comment]
Hi

Thanks mailed you from my company ID

See all this template demo or on your YouTube demo no where it says panorama in AWS is only BYOL so its kind of struggle who wants to test.

**Comment by salsop** [comment]
No problem, thanks. I'll track down the account team for you, and get them to make contacts with you.

I've also asked our Technical Marketing engineers to take a look at our documentation etc, to make the BYOL requirement more obvious, thanks for the input on this.
