### ISSUE TITLE
not getting registered in panorama

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#19]
My stack completes without any issue but not getting registered inside panorama.

I have debug enabled 

my cloudwatch /aws/lambda/xxxxxx-Init_lambda-lambda-sched-event shows below.

[ERROR]	2021-04-28T18:04:06.361Z	4303974a-4650-456e-92ea-b34935ea59f2	[RunCommand Response Fail]: HTTP Error 403: Invalid Credential
Failed to run command: https://10.xxx.xx.5/api/?type=op&cmd=<show><jobs><id>1</id></jobs></show>&key=LUFRPT1Zd2pYUGpkMUNrVEZlb3hROEQyUm95dXNGRkU9N0d4RGpTN2VZaVZYMVVoS253U0p6dlk3MkM0SDFySEh2UUR4Y3hzK2g3ST0=

any idea what wrong I am doing?

**Comment by niteenkole** [comment]
PA devices comes up and shows running I can also see them getting registered inside support portal.but not inside panorama

**Comment by niteenkole** [comment]
in https://github.com/PaloAltoNetworks/AWS-GWLB-VMSeries/blob/main/cft%20with%20autoscale/VM-Series-with-GWLB-CFT-Deployment-Guide.pdf

step 8. specify the keys for enabling API access to the firewall and panorama

1.Enter the key that the firewall must use to authenticate APIC calls.
   I have created use pandemo and password demopassword inside panorama and using the default key 

2. enter the API key to allow AWS lambda to make API call.
    Question is this is same as above key of user pandemo ?

it also ask admin user for 
Admin username for Panorama:
Enter the admin username for the Panorama instance

now again this is same pandemo ?

**Comment by niteenkole** [comment]
Never mind :)

**Comment by ssyed796** [comment]
what was the issue?

**Comment by edwinq89** [comment]
Hello @niteenkole, I've been having this problem for several days and I haven't found a solution, how did you solve it?
