### ISSUE TITLE
Question on "Specify the keys for enabling API access to the firewall and Panorama"

### ISSUE THREAD

**Issue by niteenkole** [PaloAltoNetworks/AWS-GWLB-VMSeries#20]
STEP 8 |Specify the keys for enabling API access to the firewall and Panorama.
1. Enter the key that the firewall must use to authenticate API calls. The default key is based on the
sample file and you should only use it for testing and evaluation. For a production deployment, you
must create a separate PAN-OS login just for the API call and generate an associated key.
2. Enter the API Key to allow AWS Lambda to make API calls to Panorama. For a production
deployment, you should create a separate login just for the API call and generate an associated key.

May please some help.

For 1.
This is which key ,the key we create inside panorama for user pandemo/demopassword ?

for2.
The same key which we create inside panorama for user pandemo/demopassword ?

key i am creating is like below once user is defined inside panorama

curl -k -X GET 'https://x.x.x.x.x/api/?type=keygen&user=pandemo&password=demopassword'
<response status = 'success'><result><key>LUFRPT1OWkpUYmxNME5hU25teE9KbkhUMzk2NnBRVUE9N0d4RGpTN2VZaVZYMVVoS253U0p6dWd3K1FSTW5rSUtuVXFsNWt1exxxxxxxxx==</key></result></response>/ #

for step1 if I use the default key in template I get error like (cloudwatch logs /aws/lambda/xxxxxx-Init_lambda-lambda-sched-event)
[ERROR]	2021-05-11T16:08:45.672Z	1595434d-6be9-4ef6-952f-b5f933d96404	[RunCommand Response Fail]: HTTP Error 403: Invalid Credential

Failed to run command: https://x.x.x.x./api/?type=op&cmd=<show><jobs><id>1</id></jobs></show>&key=LUFRPT1Zd2pYUGpkMUNrVEZlb3hROEQyUm95dXNGRkU9N0d4RGpTN2VZaVZYMVVoS253U0p6dlk3MkM0SDFySEh2UUR4Y3hzK2g3ST0=

**Comment by niteenkole** [comment]
Never mind :)

**Comment by Gtt1229** [comment]
How did you fix this?
