### ISSUE TITLE
Correction in Topology Diagram related to route table entries.

### ISSUE THREAD

**Issue by l4h1n** [PaloAltoNetworks/AWS-GWLB-VMSeries#4]
## Documentation link

https://github.com/PaloAltoNetworks/AWS-GWLB-VMSeries/blob/main/terraform/topology.png

## Describe the problem

The diagram doesn't mention the route to APP VPC CIDRs on gwlbe-ob-rt

## Suggested fix

Add routes to APP VPC 1 and APP VPC 2 with next hop as tgw on gwlbe-ob-rt
![topology](https://user-images.githubusercontent.com/57235922/99462750-5b455d00-295a-11eb-84d8-88a9cd1c88b9.png)

**Comment by rt696b75** [comment]
Updated the diagram.
Thanks for trying out our deployment!
