### ISSUE TITLE
init-cfg.txt config breaks bootstrapping

### ISSUE THREAD

**Issue by mattpu-sportsbet** [PaloAltoNetworks/AWS-GWLB-VMSeries#5]
## Describe the bug

The requirement for GWLB to swap the mgmt interface doesn't work with this userdata template / init-cfg file

## Expected behavior

Bootstrap / userdata config should swap mgmt interface with eth1 in order to register with the load balancer target group

## Current behavior

Firewall will deploy but without mgmt swap, so will never register until run manually

## Possible solution

As per the PA documentation, either a space OR comma should be used, not both.
https://docs.paloaltonetworks.com/vm-series/10-0/vm-series-deployment/set-up-the-vm-series-firewall-on-aws/vm-series-integration-with-gateway-load-balancer/integrate-the-vm-series-with-an-aws-gateway-load-balancer/manually-integrate-the-vm-series-with-a-gateway-load-balancer.html

Lines should be changed as follows:
/CFT_2_Firewalls/bootstrap/init-cfg.txt & /CFT_2_Firewalls/bootstrap/config/init-cfg.txt Line 13:
op-command-modes=jumbo-frame,mgmt-interface-swap
/CFT_2_Firewalls/SecurityVPC.yaml Line 995:
- op-command-modes=jumbo-frame,mgmt-interface-swap

## Steps to reproduce

Deploy this template as is, the firewalls will not become healthy on the Target Group and running the manual command to check the interface

**Comment by salsop** [comment]
Thanks for reporting this, I've fixed the issue and created a Pull Request for the team to review and merge. Let us know if you have any other issues with your deployment.

**Comment by rajp3126** [comment]
Issue resolved.

**Comment by mattpu-sportsbet** [comment]
Thanks, it doesn't look like /CFT_2_Firewalls/SecurityVPC.yaml Line 995 was updated? The userdata has the same comma and space

**Comment by salsop** [comment]
> Thanks, it doesn't look like /CFT_2_Firewalls/SecurityVPC.yaml Line 995 was updated? The userdata has the same comma and space

Sorry about that, just created another Pull Request to update it. I've requested the team review and merge in.
